/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
          "on-secondary": "#ffffff",
          "on-tertiary-fixed-variant": "#004f55",
          "primary-fixed": "#ffdad9",
          "on-error-container": "#93000a",
          "surface-container": "#ffe9e8",
          "primary-container": "#a6192e",
          "tertiary": "#00454a",
          "on-secondary-fixed": "#091d2e",
          "on-surface-variant": "#594040",
          "surface-dim": "#eed4d3",
          "inverse-surface": "#3c2c2c",
          "outline": "#8d7070",
          "on-primary-fixed-variant": "#920322",
          "on-secondary-container": "#526478",
          "surface-container-lowest": "#ffffff",
          "primary": "#81001c",
          "surface-bright": "#fff8f7",
          "surface-container-high": "#fde2e1",
          "surface": "#fff8f7",
          "on-primary-fixed": "#400009",
          "inverse-primary": "#ffb3b3",
          "surface-tint": "#b42537",
          "secondary": "#4e6073",
          "surface-container-low": "#fff0ef",
          "error-container": "#ffdad6",
          "on-tertiary": "#ffffff",
          "on-tertiary-container": "#8ed5dd",
          "primary-fixed-dim": "#ffb3b3",
          "on-background": "#261818",
          "tertiary-container": "#005e65",
          "background": "#fff8f7",
          "on-error": "#ffffff",
          "tertiary-fixed": "#a7eef6",
          "error": "#ba1a1a",
          "surface-variant": "#f7dcdc",
          "on-secondary-fixed-variant": "#36485b",
          "outline-variant": "#e1bebe",
          "inverse-on-surface": "#ffedec",
          "secondary-fixed": "#d1e4fb",
          "tertiary-fixed-dim": "#8bd2da",
          "on-tertiary-fixed": "#002022",
          "secondary-container": "#cfe2f9",
          "on-primary": "#ffffff",
          "on-surface": "#261818",
          "on-primary-container": "#ffb7b7",
          "surface-container-highest": "#f7dcdc",
          "secondary-fixed-dim": "#b5c8df"
      },
      "borderRadius": {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
      },
      "spacing": {
          "stack-lg": "24px",
          "stack-md": "16px",
          "gutter": "24px",
          "margin-page": "32px",
          "container-max-width": "1200px",
          "stack-sm": "8px",
          "unit": "8px"
      },
      "fontFamily": {
          "h1": ["Public Sans", "sans-serif"],
          "button": ["Public Sans", "sans-serif"],
          "body-lg": ["Public Sans", "sans-serif"],
          "label-caps": ["Public Sans", "sans-serif"],
          "h3": ["Public Sans", "sans-serif"],
          "h2": ["Public Sans", "sans-serif"],
          "body-sm": ["Public Sans", "sans-serif"],
          "public-sans": ["Public Sans", "sans-serif"]
      },
      "fontSize": {
          "h1": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
          "button": ["14px", {"lineHeight": "1", "fontWeight": "600"}],
          "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
          "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
          "h3": ["20px", {"lineHeight": "1.4", "fontWeight": "600"}],
          "h2": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
          "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
